from .views import (
    index,
    pricing,
    setting,
    custom_alias,
    billing,
    unsubscribe,
    api_key,
    custom_domain,
    mfa_setup,
    mfa_cancel,
    domain_detail,
    lifetime_licence,
    directory,
    mailbox,
    deleted_alias,
    alias_detail,
)
